name: Deploy docs

on: 
  push: 
    branches: 
      - master
    paths:
      - 'docs/**'

jobs: 
  deploy: 
    name: Deploy
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with: 
          node-version: '14.x'
      - run: npm ci
      - working-directory: docs
        run: |
          npm ci
          npm run build
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/content/.vitepress/dist
