name: Deploy docs

on: 
  push: 
    branches: 
      - master
    paths:
      - 'docs/**'

jobs: 
  release: 
    name: Deploy
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with: 
          node-version: '14.x'
      - run: cd docs
      - run: npm ci
      - run: npm run build
      - run: cd .vitepress/dist
      - run: git init
      - run: git add -A
      - run: git commit -m 'deploy'
      - run: git commit -m 'deploy'
      - run: git push -f git@github.com:vueup/vueup-quill.git master:gh-pages
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
