name: Release package

on: 
  push: 
    branches: 
      - alpha
      - beta
      - master
    paths-ignore:
      - 'docs/**'
      - 'scripts/**'
      - '**/README.md'
      - '**/.gitignore'
      - '.github/*.yml'

jobs: 
  release: 
    name: Build and release
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '14.x'
      - name: Build package
        run: | 
          npm ci
          npm run theme:build
          npm run lib:build
      - name: Release package
        run: npx semantic-release
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN}}